suppressPackageStartupMessages(library(SoupX))
x = load10X(snakemake@input[[1]])
pdf(snakemake@output[[1]], width=6, height=4)
x = autoEstCont(x)
dev.off()
x = adjustCounts(x, roundToInt=T)
suppressPackageStartupMessages(library(DropletUtils))
write10xCounts(snakemake@output[[2]], x)
